# Generated by Django 5.2.4 on 2025-08-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_mock',
            field=models.BooleanField(default=False),
        ),
    ]
