# Generated by Django 5.2.4 on 2025-08-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_bio_remove_user_is_mock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mock',
            field=models.BooleanField(default=False),
        ),
    ]
